language: go
go:
  - 1.19.x
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci
